### ISSUE TITLE
Problem running 01 --local

### ISSUE THREAD

**Issue by MikeBirdTech** [KillianLucas/01#54]
I ran `01 --local` for the first time. It went through the install process and then prompted me to press spacebar to start recording. After recording stopped, I got this error:

I am on a Macbook pro

```
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.1.0.2.5)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.1.1_3 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopenvino --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[aist#0:0/pcm_s16le @ 0x135705910] Guessed Channel Layout: mono
Input #0, wav, from '/var/folders/7z/qhl_78mx1sz4yjtmfy1md90w0000gn/T/audio_20240224172112420692.wav':
  Duration: 00:00:01.56, bitrate: 705 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 1 channels, s16, 705 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '/var/folders/7z/qhl_78mx1sz4yjtmfy1md90w0000gn/T/output_stt_20240224172114115969.wav':
  Metadata:
    ISFT            : Lavf60.16.100
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc60.31.102 pcm_s16le
[out#0/wav @ 0x6000009d83c0] video:0kB audio:49kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.156677%
size=      49kB time=00:00:01.55 bitrate= 256.6kbits/s speed= 734x
Exception in thread Thread-7 (record_audio):
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/01/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/anaconda3/envs/01/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/anaconda3/envs/01/lib/python3.11/site-packages/01OS/clients/base_device.py", line 185, in record_audio
    text = stt_wav(wav_path)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/01/lib/python3.11/site-packages/01OS/server/stt/stt.py", line 112, in stt_wav
    transcript = get_transcription_file(output_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/01/lib/python3.11/site-packages/01OS/server/stt/stt.py", line 76, in get_transcription_file
    output, error = run_command([
                    ^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/01/lib/python3.11/site-packages/01OS/server/stt/stt.py", line 66, in run_command
    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/01/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/01/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/anaconda3/envs/01/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/anaconda3/envs/01/lib/python3.11/site-packages/01OS/server/stt/whisper-rust/target/release/whisper-rust'
```

**Comment by shivenmian** [comment]
Seems like whisper-rust is not built. Try running `poetry run 01 --local`

**Comment by shivenmian** [comment]
Fixed by installing cmake
